# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hactl < Formula
  desc "Home Assistant control CLI, built for agentic workflows"
  homepage "https://github.com/hemm-ems/hactl"
  version "2026.7.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hemm-ems/hactl/releases/download/v2026.7.4/hactl_2026.7.4_darwin_amd64.tar.gz"
      sha256 "02721ae5089ed601af5a68c259d9bc011dd817e1391be95803ddb290cbdd5056"

      define_method(:install) do
        bin.install "hactl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hemm-ems/hactl/releases/download/v2026.7.4/hactl_2026.7.4_darwin_arm64.tar.gz"
      sha256 "272d34d6447f53ed0aaca6ac53639152f997c02f98731c0699c8db3517df6173"

      define_method(:install) do
        bin.install "hactl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hemm-ems/hactl/releases/download/v2026.7.4/hactl_2026.7.4_linux_amd64.tar.gz"
      sha256 "f9d1aca1f94dcb1d3802a5f30730db41435292d036dc6ab0d5483d8fae3e811c"
      define_method(:install) do
        bin.install "hactl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hemm-ems/hactl/releases/download/v2026.7.4/hactl_2026.7.4_linux_arm64.tar.gz"
      sha256 "a429923d8a744be69e7ca89b653fa796b377ec05df1c7c1b0b83a1a02eba70b2"
      define_method(:install) do
        bin.install "hactl"
      end
    end
  end

  test do
    system "#{bin}/hactl", "--version"
  end
end
