# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hactl < Formula
  desc "Home Assistant control CLI, built for agentic workflows"
  homepage "https://github.com/hemm-ems/hactl"
  version "2026.7.13"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hemm-ems/hactl/releases/download/v2026.7.13/hactl_2026.7.13_darwin_amd64.tar.gz"
      sha256 "7afc06dff33bb886f065643b85e807893988b02bf2a6001518139fdc9ad181d9"

      define_method(:install) do
        bin.install "hactl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hemm-ems/hactl/releases/download/v2026.7.13/hactl_2026.7.13_darwin_arm64.tar.gz"
      sha256 "524920d5511279bac3cab019173da5103f4e18c21c15dd66913fe4138a504ea8"

      define_method(:install) do
        bin.install "hactl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hemm-ems/hactl/releases/download/v2026.7.13/hactl_2026.7.13_linux_amd64.tar.gz"
      sha256 "9521daae618edac0f32354f3a782ca6ebeda8b81c786a02528e44d0b3d3a07f0"
      define_method(:install) do
        bin.install "hactl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hemm-ems/hactl/releases/download/v2026.7.13/hactl_2026.7.13_linux_arm64.tar.gz"
      sha256 "017b9ee839148eef7d88c1e16bb00ea25ed1c3a09f36ad1bdd217efaace414f5"
      define_method(:install) do
        bin.install "hactl"
      end
    end
  end

  test do
    system "#{bin}/hactl", "--version"
  end
end
